name: Deploy Frontend to S3

on:
  push:
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies and build
        working-directory: ./frontend
        run: |
          npm ci
          npm run build

      - name: Upload to S3 using AWS CLI
        run: |
          aws s3 sync ./frontend/build s3://${{ secrets.S3_BUCKET }} --delete
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}